In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("titanic/test.csv")

In [5]:
npdf=df.to_numpy()
print(npdf)

[[892 3 'Kelly, Mr. James' ... 7.8292 nan 'Q']
 [893 3 'Wilkes, Mrs. James (Ellen Needs)' ... 7.0 nan 'S']
 [894 2 'Myles, Mr. Thomas Francis' ... 9.6875 nan 'Q']
 ...
 [1307 3 'Saether, Mr. Simon Sivertsen' ... 7.25 nan 'S']
 [1308 3 'Ware, Mr. Frederick' ... 8.05 nan 'S']
 [1309 3 'Peter, Master. Michael J' ... 22.3583 nan 'C']]

In [8]:
npage=df["Age"].dropna().to_numpy()
print(np.mean(npage))
print(np.median(npage))
print(np.std(npage))
print(np.min(npage))
print(np.max(npage))

30.272590361445783
27.0
14.159835886272559
0.17
76.0

In [16]:
df.loc[df["Age"]==0.17,["Name","Age","Sex"]]

                                        Name   Age     Sex
354  Dean, Miss. Elizabeth Gladys Millvina""  0.17  female

In [17]:
df.loc[df["Age"]==76.0,["Name","Age","Sex"]]

                                                 Name   Age     Sex
96  Cavendish, Mrs. Tyrell William (Julia Florence...  76.0  female

In [18]:
df.loc[df["Age"]>40,["Name","Age","Sex"]]

                                                  Name   Age     Sex
1                     Wilkes, Mrs. James (Ellen Needs)  47.0  female
2                            Myles, Mr. Thomas Francis  62.0    male
11                          Jones, Mr. Charles Cresson  46.0    male
13                                Howard, Mr. Benjamin  63.0    male
14   Chaffee, Mrs. Herbert Fuller (Carrie Constance...  47.0  female
..                                                 ...   ...     ...
391     Lines, Mrs. Ernest H (Elizabeth Lindsey James)  51.0  female
393                               Gilbert, Mr. William  47.0    male
397  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...  48.0  female
404                       Frauenthal, Mr. Isaac Gerald  43.0    male
407                         Widener, Mr. George Dunton  50.0    male

[77 rows x 3 columns]

In [20]:
for i in enumerate(df.columns):
    print(i)

(0, 'PassengerId')
(1, 'Pclass')
(2, 'Name')
(3, 'Sex')
(4, 'Age')
(5, 'SibSp')
(6, 'Parch')
(7, 'Ticket')
(8, 'Fare')
(9, 'Cabin')
(10, 'Embarked')

In [23]:
df.iloc[0:5,2:5]

                                           Name     Sex   Age
0                              Kelly, Mr. James    male  34.5
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0
2                     Myles, Mr. Thomas Francis    male  62.0
3                              Wirz, Mr. Albert    male  27.0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0

git hub find the no of vdos in laproscopic surgery